name: myui
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=3.3.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.6
    bitsdojo_window: ^0.1.6
    flutter_acrylic: ^1.1.3
    get: ^4.6.6
    crypto: ^3.0.3
    http: ^1.2.1
    path_provider: ^2.1.3
    image_picker: ^1.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/plugins/draw.png
    fonts:
        - family: Hiragino Sans
          fonts:
              - asset: assets/fonts/Hiragino Sans GB.ttc
        - family: iconfont
          fonts:
              - asset: assets/fonts/iconfont.ttf
